#ifndef DEFINE_HEADERS
#define DEFINE_HEADERS
#define SCREEN_WIDTH	1280
#define SCREEN_HEIGHT	720

#define MAX_KEYBOARD_KEYS 350

#define PLAYER_SPEED          4
#define PLAYER_BULLET_SPEED   16
#define PLAYER_RELOAD   15

#define SIDE_PLAYER 0
#define SIDE_ALIEN  1

#define FPS 60

#define ALIEN_BULLET_SPEED    5

#endif